# SPDX-FileCopyrightText: 2026 Andrea Mazzucchi <andrea.mazzucchi@tutamail.com>
# SPDX-FileCopyrightText: 2026 Francesco Quaglia <francesco.quaglia@uniroma2.it>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#this Makefile is just for builfing user-defined stuff if any
#if you do no need please leave ut siply with an idempotent 
# "all" command

all:
	gcc translate-to-binary.c -o translate-to-binary
